import azure.cognitiveservices.speech as speechsdk

speech_key, service_region = "", "northeurope"

def speech_synthesis_with_voice():
    """performs speech synthesis to the default speaker with specified voice"""
    # Creates an instance of a speech config with specified subscription key and service region.
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    # Sets the synthesis voice name.
    # e.g. "Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)".
    # The full list of supported voices can be found here:
    # https://aka.ms/csspeech/voicenames
    # And, you can try get_voices_async method to get all available voices (see speech_synthesis_get_available_voices() sample below).
    voice = "Microsoft Server Speech Text to Speech Voice (en-AU, WilliamNeural)"
    speech_config.speech_synthesis_voice_name = voice
    # Creates a speech synthesizer for the specified voice,
    # using the default speaker as audio output.
    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config)

    # Receives a text from console input and synthesizes it to speaker.
    while True:
        print("Enter some text that you want to speak, Ctrl-Z to exit")
        try:
            text = input()
        except EOFError:
            break
        result = speech_synthesizer.speak_text_async(text).get()
        # Check result
        if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
            print("Speech synthesized to speaker for text [{}] with voice [{}]".format(text, voice))
        elif result.reason == speechsdk.ResultReason.Canceled:
            cancellation_details = result.cancellation_details
            print("Speech synthesis canceled: {}".format(cancellation_details.reason))
            if cancellation_details.reason == speechsdk.CancellationReason.Error:
                print("Error details: {}".format(cancellation_details.error_details))

def speech_synthesis_get_available_voices():
    """gets the available voices list."""

    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    # Creates a speech synthesizer.
    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=None)

    print("Enter a locale in BCP-47 format (e.g. en-US) that you want to get the voices of, or enter empty to get voices in all locales.")
    try:
        text = input()
    except EOFError:
        pass

    result = speech_synthesizer.get_voices_async(text).get()
    # Check result
    if result.reason == speechsdk.ResultReason.VoicesListRetrieved:
        print('Voices successfully retrieved, they are:')
        for voice in result.voices:
            print(voice.name)
    elif result.reason == speechsdk.ResultReason.Canceled:
        print("Speech synthesis canceled; error details: {}".format(result.error_details))

#speech_synthesis_get_available_voices()
speech_synthesis_with_voice()

"""Microsoft Server Speech Text to Speech Voice (ar-EG, SalmaNeural)
Microsoft Server Speech Text to Speech Voice (ar-EG, ShakirNeural)
Microsoft Server Speech Text to Speech Voice (ar-EG, Hoda)
Microsoft Server Speech Text to Speech Voice (ar-SA, HamedNeural)
Microsoft Server Speech Text to Speech Voice (ar-SA, ZariyahNeural)
Microsoft Server Speech Text to Speech Voice (ar-SA, Naayf)
Microsoft Server Speech Text to Speech Voice (bg-BG, BorislavNeural)
Microsoft Server Speech Text to Speech Voice (bg-BG, KalinaNeural)
Microsoft Server Speech Text to Speech Voice (bg-BG, Ivan)
Microsoft Server Speech Text to Speech Voice (ca-ES, JoanaNeural)
Microsoft Server Speech Text to Speech Voice (ca-ES, AlbaNeural)
Microsoft Server Speech Text to Speech Voice (ca-ES, EnricNeural)
Microsoft Server Speech Text to Speech Voice (ca-ES, HerenaRUS)
Microsoft Server Speech Text to Speech Voice (cs-CZ, AntoninNeural)
Microsoft Server Speech Text to Speech Voice (cs-CZ, VlastaNeural)
Microsoft Server Speech Text to Speech Voice (cs-CZ, Jakub)
Microsoft Server Speech Text to Speech Voice (cy-GB, AledNeural)
Microsoft Server Speech Text to Speech Voice (cy-GB, NiaNeural)
Microsoft Server Speech Text to Speech Voice (da-DK, ChristelNeural)
Microsoft Server Speech Text to Speech Voice (da-DK, JeppeNeural)
Microsoft Server Speech Text to Speech Voice (da-DK, HelleRUS)
Microsoft Server Speech Text to Speech Voice (de-AT, IngridNeural)
Microsoft Server Speech Text to Speech Voice (de-AT, JonasNeural)
Microsoft Server Speech Text to Speech Voice (de-AT, Michael)
Microsoft Server Speech Text to Speech Voice (de-CH, JanNeural)
Microsoft Server Speech Text to Speech Voice (de-CH, LeniNeural)
Microsoft Server Speech Text to Speech Voice (de-CH, Karsten)
Microsoft Server Speech Text to Speech Voice (de-DE, KatjaNeural)
Microsoft Server Speech Text to Speech Voice (de-DE, ConradNeural)
Microsoft Server Speech Text to Speech Voice (de-DE, HeddaRUS)
Microsoft Server Speech Text to Speech Voice (de-DE, Stefan)
Microsoft Server Speech Text to Speech Voice (el-GR, AthinaNeural)
Microsoft Server Speech Text to Speech Voice (el-GR, NestorasNeural)
Microsoft Server Speech Text to Speech Voice (el-GR, Stefanos)
Microsoft Server Speech Text to Speech Voice (en-AU, NatashaNeural)
Microsoft Server Speech Text to Speech Voice (en-AU, WilliamNeural)
Microsoft Server Speech Text to Speech Voice (en-AU, Catherine)
Microsoft Server Speech Text to Speech Voice (en-AU, HayleyRUS)
Microsoft Server Speech Text to Speech Voice (en-CA, ClaraNeural)
Microsoft Server Speech Text to Speech Voice (en-CA, LiamNeural)
Microsoft Server Speech Text to Speech Voice (en-CA, HeatherRUS)
Microsoft Server Speech Text to Speech Voice (en-CA, Linda)
Microsoft Server Speech Text to Speech Voice (en-GB, MiaNeural)
Microsoft Server Speech Text to Speech Voice (en-GB, LibbyNeural)
Microsoft Server Speech Text to Speech Voice (en-GB, RyanNeural)
Microsoft Server Speech Text to Speech Voice (en-GB, George)
Microsoft Server Speech Text to Speech Voice (en-GB, HazelRUS)
Microsoft Server Speech Text to Speech Voice (en-GB, Susan)
Microsoft Server Speech Text to Speech Voice (en-IE, ConnorNeural)
Microsoft Server Speech Text to Speech Voice (en-IE, EmilyNeural)
Microsoft Server Speech Text to Speech Voice (en-IE, Sean)
Microsoft Server Speech Text to Speech Voice (en-IN, NeerjaNeural)
Microsoft Server Speech Text to Speech Voice (en-IN, PrabhatNeural)
Microsoft Server Speech Text to Speech Voice (en-IN, Heera)
Microsoft Server Speech Text to Speech Voice (en-IN, PriyaRUS)
Microsoft Server Speech Text to Speech Voice (en-IN, Ravi)
Microsoft Server Speech Text to Speech Voice (en-PH, JamesNeural)
Microsoft Server Speech Text to Speech Voice (en-PH, RosaNeural)
Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)
Microsoft Server Speech Text to Speech Voice (en-US, GuyNeural)
Microsoft Server Speech Text to Speech Voice (en-US, AriaNeural)
Microsoft Server Speech Text to Speech Voice (en-US, AriaRUS)
Microsoft Server Speech Text to Speech Voice (en-US, BenjaminRUS)
Microsoft Server Speech Text to Speech Voice (en-US, GuyRUS)
Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)
Microsoft Server Speech Text to Speech Voice (es-ES, AlvaroNeural)
Microsoft Server Speech Text to Speech Voice (es-ES, ElviraNeural)
Microsoft Server Speech Text to Speech Voice (es-ES, HelenaRUS)
Microsoft Server Speech Text to Speech Voice (es-ES, Laura)
Microsoft Server Speech Text to Speech Voice (es-ES, Pablo)
Microsoft Server Speech Text to Speech Voice (es-MX, DaliaNeural)
Microsoft Server Speech Text to Speech Voice (es-MX, JorgeNeural)
Microsoft Server Speech Text to Speech Voice (es-MX, HildaRUS)
Microsoft Server Speech Text to Speech Voice (es-MX, Raul)
Microsoft Server Speech Text to Speech Voice (et-EE, AnuNeural)
Microsoft Server Speech Text to Speech Voice (et-EE, KertNeural)
Microsoft Server Speech Text to Speech Voice (fi-FI, SelmaNeural)
Microsoft Server Speech Text to Speech Voice (fi-FI, HarriNeural)
Microsoft Server Speech Text to Speech Voice (fi-FI, NooraNeural)
Microsoft Server Speech Text to Speech Voice (fi-FI, HeidiRUS)
Microsoft Server Speech Text to Speech Voice (fr-BE, CharlineNeural)
Microsoft Server Speech Text to Speech Voice (fr-BE, GerardNeural)
Microsoft Server Speech Text to Speech Voice (fr-CA, SylvieNeural)
Microsoft Server Speech Text to Speech Voice (fr-CA, AntoineNeural)
Microsoft Server Speech Text to Speech Voice (fr-CA, JeanNeural)
Microsoft Server Speech Text to Speech Voice (fr-CA, Caroline)
Microsoft Server Speech Text to Speech Voice (fr-CA, HarmonieRUS)
Microsoft Server Speech Text to Speech Voice (fr-CH, ArianeNeural)
Microsoft Server Speech Text to Speech Voice (fr-CH, FabriceNeural)
Microsoft Server Speech Text to Speech Voice (fr-CH, Guillaume)
Microsoft Server Speech Text to Speech Voice (fr-FR, DeniseNeural)
Microsoft Server Speech Text to Speech Voice (fr-FR, HenriNeural)
Microsoft Server Speech Text to Speech Voice (fr-FR, HortenseRUS)
Microsoft Server Speech Text to Speech Voice (fr-FR, Julie)
Microsoft Server Speech Text to Speech Voice (fr-FR, Paul)
Microsoft Server Speech Text to Speech Voice (ga-IE, ColmNeural)
Microsoft Server Speech Text to Speech Voice (ga-IE, OrlaNeural)
Microsoft Server Speech Text to Speech Voice (he-IL, AvriNeural)
Microsoft Server Speech Text to Speech Voice (he-IL, HilaNeural)
Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)
Microsoft Server Speech Text to Speech Voice (hi-IN, MadhurNeural)
Microsoft Server Speech Text to Speech Voice (hi-IN, SwaraNeural)
Microsoft Server Speech Text to Speech Voice (hi-IN, Hemant)
Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana)
Microsoft Server Speech Text to Speech Voice (hr-HR, GabrijelaNeural)
Microsoft Server Speech Text to Speech Voice (hr-HR, SreckoNeural)
Microsoft Server Speech Text to Speech Voice (hr-HR, Matej)
Microsoft Server Speech Text to Speech Voice (hu-HU, NoemiNeural)
Microsoft Server Speech Text to Speech Voice (hu-HU, TamasNeural)
Microsoft Server Speech Text to Speech Voice (hu-HU, Szabolcs)
Microsoft Server Speech Text to Speech Voice (id-ID, ArdiNeural)
Microsoft Server Speech Text to Speech Voice (id-ID, GadisNeural)
Microsoft Server Speech Text to Speech Voice (id-ID, Andika)
Microsoft Server Speech Text to Speech Voice (it-IT, IsabellaNeural)
Microsoft Server Speech Text to Speech Voice (it-IT, DiegoNeural)
Microsoft Server Speech Text to Speech Voice (it-IT, ElsaNeural)
Microsoft Server Speech Text to Speech Voice (it-IT, Cosimo)
Microsoft Server Speech Text to Speech Voice (it-IT, LuciaRUS)
Microsoft Server Speech Text to Speech Voice (ja-JP, NanamiNeural)
Microsoft Server Speech Text to Speech Voice (ja-JP, KeitaNeural)
Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi)
Microsoft Server Speech Text to Speech Voice (ja-JP, HarukaRUS)
Microsoft Server Speech Text to Speech Voice (ja-JP, Ichiro)
Microsoft Server Speech Text to Speech Voice (ko-KR, SunHiNeural)
Microsoft Server Speech Text to Speech Voice (ko-KR, InJoonNeural)
Microsoft Server Speech Text to Speech Voice (ko-KR, HeamiRUS)
Microsoft Server Speech Text to Speech Voice (lt-LT, LeonasNeural)
Microsoft Server Speech Text to Speech Voice (lt-LT, OnaNeural)
Microsoft Server Speech Text to Speech Voice (lv-LV, EveritaNeural)
Microsoft Server Speech Text to Speech Voice (lv-LV, NilsNeural)
Microsoft Server Speech Text to Speech Voice (ms-MY, OsmanNeural)
Microsoft Server Speech Text to Speech Voice (ms-MY, YasminNeural)
Microsoft Server Speech Text to Speech Voice (ms-MY, Rizwan)
Microsoft Server Speech Text to Speech Voice (mt-MT, GraceNeural)
Microsoft Server Speech Text to Speech Voice (mt-MT, JosephNeural)
Microsoft Server Speech Text to Speech Voice (nb-NO, PernilleNeural)
Microsoft Server Speech Text to Speech Voice (nb-NO, FinnNeural)
Microsoft Server Speech Text to Speech Voice (nb-NO, IselinNeural)
Microsoft Server Speech Text to Speech Voice (nb-NO, HuldaRUS)
Microsoft Server Speech Text to Speech Voice (nl-BE, ArnaudNeural)
Microsoft Server Speech Text to Speech Voice (nl-BE, DenaNeural)
Microsoft Server Speech Text to Speech Voice (nl-NL, ColetteNeural)
Microsoft Server Speech Text to Speech Voice (nl-NL, FennaNeural)
Microsoft Server Speech Text to Speech Voice (nl-NL, MaartenNeural)
Microsoft Server Speech Text to Speech Voice (nl-NL, HannaRUS)
Microsoft Server Speech Text to Speech Voice (pl-PL, AgnieszkaNeural)
Microsoft Server Speech Text to Speech Voice (pl-PL, MarekNeural)
Microsoft Server Speech Text to Speech Voice (pl-PL, ZofiaNeural)
Microsoft Server Speech Text to Speech Voice (pl-PL, PaulinaRUS)
Microsoft Server Speech Text to Speech Voice (pt-BR, FranciscaNeural)
Microsoft Server Speech Text to Speech Voice (pt-BR, AntonioNeural)
Microsoft Server Speech Text to Speech Voice (pt-BR, Daniel)
Microsoft Server Speech Text to Speech Voice (pt-BR, HeloisaRUS)
Microsoft Server Speech Text to Speech Voice (pt-PT, DuarteNeural)
Microsoft Server Speech Text to Speech Voice (pt-PT, FernandaNeural)
Microsoft Server Speech Text to Speech Voice (pt-PT, RaquelNeural)
Microsoft Server Speech Text to Speech Voice (pt-PT, HeliaRUS)
Microsoft Server Speech Text to Speech Voice (ro-RO, AlinaNeural)
Microsoft Server Speech Text to Speech Voice (ro-RO, EmilNeural)
Microsoft Server Speech Text to Speech Voice (ro-RO, Andrei)
Microsoft Server Speech Text to Speech Voice (ru-RU, SvetlanaNeural)
Microsoft Server Speech Text to Speech Voice (ru-RU, DariyaNeural)
Microsoft Server Speech Text to Speech Voice (ru-RU, DmitryNeural)
Microsoft Server Speech Text to Speech Voice (ru-RU, EkaterinaRUS)
Microsoft Server Speech Text to Speech Voice (ru-RU, Irina)
Microsoft Server Speech Text to Speech Voice (ru-RU, Pavel)
Microsoft Server Speech Text to Speech Voice (sk-SK, LukasNeural)
Microsoft Server Speech Text to Speech Voice (sk-SK, ViktoriaNeural)
Microsoft Server Speech Text to Speech Voice (sk-SK, Filip)
Microsoft Server Speech Text to Speech Voice (sl-SI, PetraNeural)
Microsoft Server Speech Text to Speech Voice (sl-SI, RokNeural)
Microsoft Server Speech Text to Speech Voice (sl-SI, Lado)
Microsoft Server Speech Text to Speech Voice (sv-SE, SofieNeural)
Microsoft Server Speech Text to Speech Voice (sv-SE, HilleviNeural)
Microsoft Server Speech Text to Speech Voice (sv-SE, MattiasNeural)
Microsoft Server Speech Text to Speech Voice (sv-SE, HedvigRUS)
Microsoft Server Speech Text to Speech Voice (ta-IN, PallaviNeural)
Microsoft Server Speech Text to Speech Voice (ta-IN, ValluvarNeural)
Microsoft Server Speech Text to Speech Voice (ta-IN, Valluvar)
Microsoft Server Speech Text to Speech Voice (te-IN, MohanNeural)
Microsoft Server Speech Text to Speech Voice (te-IN, ShrutiNeural)
Microsoft Server Speech Text to Speech Voice (te-IN, Chitra)
Microsoft Server Speech Text to Speech Voice (th-TH, PremwadeeNeural)
Microsoft Server Speech Text to Speech Voice (th-TH, AcharaNeural)
Microsoft Server Speech Text to Speech Voice (th-TH, NiwatNeural)
Microsoft Server Speech Text to Speech Voice (th-TH, Pattara)
Microsoft Server Speech Text to Speech Voice (tr-TR, AhmetNeural)
Microsoft Server Speech Text to Speech Voice (tr-TR, EmelNeural)
Microsoft Server Speech Text to Speech Voice (tr-TR, SedaRUS)
Microsoft Server Speech Text to Speech Voice (uk-UA, OstapNeural)
Microsoft Server Speech Text to Speech Voice (uk-UA, PolinaNeural)
Microsoft Server Speech Text to Speech Voice (ur-PK, AsadNeural)
Microsoft Server Speech Text to Speech Voice (ur-PK, UzmaNeural)
Microsoft Server Speech Text to Speech Voice (vi-VN, HoaiMyNeural)
Microsoft Server Speech Text to Speech Voice (vi-VN, NamMinhNeural)
Microsoft Server Speech Text to Speech Voice (vi-VN, An)
Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoxiaoNeural)
Microsoft Server Speech Text to Speech Voice (zh-CN, YunyangNeural)
Microsoft Server Speech Text to Speech Voice (zh-CN, XiaoyouNeural)
Microsoft Server Speech Text to Speech Voice (zh-CN, YunyeNeural)
Microsoft Server Speech Text to Speech Voice (zh-CN, HuihuiRUS)
Microsoft Server Speech Text to Speech Voice (zh-CN, Kangkang)
Microsoft Server Speech Text to Speech Voice (zh-CN, Yaoyao)
Microsoft Server Speech Text to Speech Voice (zh-HK, HiuMaanNeural)
Microsoft Server Speech Text to Speech Voice (zh-HK, HiuGaaiNeural)
Microsoft Server Speech Text to Speech Voice (zh-HK, WanLungNeural)
Microsoft Server Speech Text to Speech Voice (zh-HK, Danny)
Microsoft Server Speech Text to Speech Voice (zh-HK, TracyRUS)
Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoChenNeural)
Microsoft Server Speech Text to Speech Voice (zh-TW, HsiaoYuNeural)
Microsoft Server Speech Text to Speech Voice (zh-TW, YunJheNeural)
Microsoft Server Speech Text to Speech Voice (zh-TW, HanHanRUS)
Microsoft Server Speech Text to Speech Voice (zh-TW, Yating)
Microsoft Server Speech Text to Speech Voice (zh-TW, Zhiwei)

Process finished with exit code 0
"""